"""Initial migration

Revision ID: 4e2a18524cc6
Revises: 
Create Date: 2025-02-13 12:47:18.522089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2a18524cc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('tweet_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_metrics_account_id'), 'account_metrics', ['account_id'], unique=True)
    op.create_index(op.f('ix_account_metrics_id'), 'account_metrics', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_table('viral_tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('retweet_ratio', sa.Float(), nullable=True),
    sa.Column('like_ratio', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_tweets_id'), 'viral_tweets', ['id'], unique=False)
    op.create_index(op.f('ix_viral_tweets_tweet_id'), 'viral_tweets', ['tweet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viral_tweets_tweet_id'), table_name='viral_tweets')
    op.drop_index(op.f('ix_viral_tweets_id'), table_name='viral_tweets')
    op.drop_table('viral_tweets')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_account_metrics_id'), table_name='account_metrics')
    op.drop_index(op.f('ix_account_metrics_account_id'), table_name='account_metrics')
    op.drop_table('account_metrics')
    # ### end Alembic commands ###
