"""adaptation_settings

Revision ID: 9626128cf231
Revises: 4e2a18524cc6
Create Date: 2025-02-13 17:15:52.348345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9626128cf231'
down_revision: Union[str, None] = '4e2a18524cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viral_tweet_id', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('result_metrics', sa.String(), nullable=True),
    sa.Column('adaptation_parameters', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_logs_id'), 'adaptation_logs', ['id'], unique=False)
    op.create_table('adaptation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viral_threshold', sa.Float(), nullable=True),
    sa.Column('generation_style', sa.String(), nullable=True),
    sa.Column('posting_interval', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_settings_id'), 'adaptation_settings', ['id'], unique=False)
    op.add_column('viral_tweets', sa.Column('analysis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viral_tweets', 'analysis')
    op.drop_index(op.f('ix_adaptation_settings_id'), table_name='adaptation_settings')
    op.drop_table('adaptation_settings')
    op.drop_index(op.f('ix_adaptation_logs_id'), table_name='adaptation_logs')
    op.drop_table('adaptation_logs')
    # ### end Alembic commands ###
