"""Add correction

Revision ID: e54646544048
Revises: 9626128cf231
Create Date: 2025-02-15 05:54:59.195167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54646544048'
down_revision: Union[str, None] = '9626128cf231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adaptation_settings', sa.Column('correction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adaptation_settings', 'correction')
    # ### end Alembic commands ###
